### PR TITLE
BUG: Fix old reference to vtkCurveGenerator in MarkupsToModel

### LINKED ISSUE #16: DrawTube effect doesn't load for current Slicer nightly
The following traceback occurs after installing this extension in the current Slicer nightly build. It appears to be caused by https://github.com/SlicerIGT/SlicerMarkupsToModel/commit/7612c4275a50d0d5d5222f90e37a40bdee7511f8.  @lassoan Do you want to go ahead and make a 4.10 branch for this repo as was done in the MarkupsToModel repo?  Then the DrawTube effect can work in both the Slicer nightly and in Slicer stable.

```powershell
Traceback (most recent call last):
  File "C:/Users/james/AppData/Roaming/NA-MIC/Extensions-28040/SegmentEditorExtraEffects/lib/Slicer-4.11/qt-scripted-modules/SegmentEditorDrawTubeLib/SegmentEditorEffect.py", line 14, in __init__
    self.logic = DrawTubeLogic(scriptedEffect)
  File "C:/Users/james/AppData/Roaming/NA-MIC/Extensions-28040/SegmentEditorExtraEffects/lib/Slicer-4.11/qt-scripted-modules/SegmentEditorDrawTubeLib/SegmentEditorEffect.py", line 363, in __init__
    self.curveGenerator = vtkSlicerMarkupsToModelModuleLogicPython.vtkCurveGenerator()
AttributeError: 'module' object has no attribute 'vtkCurveGenerator'
Traceback (most recent call last):
  File "C:/Users/james/AppData/Roaming/NA-MIC/Extensions-28040/SegmentEditorExtraEffects/lib/Slicer-4.11/qt-scripted-modules/SegmentEditorDrawTube.py", line 27, in registerEditorEffect
    instance.self().register()
AttributeError: 'NoneType' object has no attribute 'register'
```

### PR DESCRIPTION
**Pull request by jamesobutler**
This closes #16 and works for both the latest stable (Slicer 4.10.1) and the current Slicer nightly.

### CODE REVIEW

**Comment by lassoan** [comment]
Thank you!
